- name: Descargar e instalar el paquete RPM de Elasticsearch
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.11.1-x86_64.rpm
    state: present

- name: Desplegar la configuración de Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Habilitar y arrancar el servicio de Filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: started
    daemon_reload: yes
