- name: Crear directorio para la aplicación de logger 3
  file:
    path: /opt/logger_app_3
    state: directory

- name: Crear directorio de logs para la aplicación de logger 3
  file:
    path: /var/log/logger_app_3
    state: directory
    mode: '0755'

- name: Asegurar que el directorio de logs existe y tiene permisos adecuados
  file:
    path: /var/log/logger_app_3
    state: directory
    owner: nobody
    group: nobody
    mode: '0755'

- name: Crear archivo de log con permisos adecuados si no existe
  file:
    path: /var/log/logger_app_3/app.log
    state: touch
    owner: nobody
    group: nobody
    mode: '0644'

- name: Desplegar el script de la aplicación de logger 3
  template:
    src: logger_app_3.sh.j2
    dest: /opt/logger_app_3/logger_app_3.sh
    mode: '0755'

- name: Desplegar el servicio de la aplicación de logger 3
  template:
    src: logger_app_3.service.j2
    dest: /etc/systemd/system/logger_app_3.service

- name: Habilitar y arrancar el servicio de la aplicación de logger 3
  systemd:
    name: logger_app_3
    enabled: yes
    state: started
    daemon_reload: yes
