- name: Descargar script de configuración de NodeSource para Node.js
  get_url:
    url: https://rpm.nodesource.com/setup_14.x
    dest: /tmp/setup_node.sh
    mode: '0755'

- name: Ejecutar script de configuración de NodeSource
  command: sh /tmp/setup_node.sh
  args:
    creates: /etc/yum.repos.d/nodesource-el.repo

- name: Instalar Node.js y npm
  yum:
    name: nodejs
    state: present

